
object Flags {
  // TODO: Order of words matter!

  val NGRAM_HALF_LENGTH = 2
  val MIN_NGRAM_DIST = 2 * NGRAM_HALF_LENGTH
  val MAX_SIMILAR_WORDS = 20
  val NGRAM_DIST_FROM_CENTER_PENALTY_BASE = 3
  val NGRAM_WORD_POPULARITY_PENALTY_BASE = 3
  val WORD_SIMILARITY_PROMOTION_BASE = 1.2
}
